-- Table: public.users
-- DROP TABLE public.users;

CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;
    

-- Table: public.addresses
-- DROP TABLE public.addresses;
CREATE TABLE public.addresses
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    address character varying(255) COLLATE pg_catalog."default",
    country character varying(255) COLLATE pg_catalog."default",
    user_id bigint,
    CONSTRAINT addresses_pkey PRIMARY KEY (id),
    CONSTRAINT fk1fa36y2oqhao3wgg2rw1pi459 FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

TABLESPACE pg_default;

ALTER TABLE public.addresses
    OWNER to postgres;